### ISSUE TITLE
Bit manipulation doesn't work with floats.

### ISSUE THREAD

**Issue by OmeGaster** [freedom7341/FuzzyMath#2]
We probably need to add a function in the fuzzy_mult_loop to multiply the original number by a certain magnitude of 10 that makes it into a whole number, then divide it by that same magnitude at the end

**Comment by freedom7341** [comment]
Since we have sigfigs we could use those to figure out how many times to multiply by 10 to get a shiftable integer result.

**Comment by OmeGaster** [comment]
Ooh, good catch! I'll implement it
